name: magiccraft_wallet
description: A magical EVM wallet for MagicCraft
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.3

  # State Management
  provider: ^6.1.1

  # Web3 & Crypto
  web3dart: ^2.7.3
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  crypto: ^3.0.3

  # Security & Storage
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.6

  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  # UI & Navigation
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Network & HTTP
  http: ^1.1.0
  dio: ^5.3.2

  # Utils
  intl: ^0.18.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #assets:
    # Make sure these folders exist and contain files
    #- assets/images/
   # - assets/icons/

  fonts:
    - family: MagicCraft
      fonts:
        - asset: assets/fonts/Minecraft.ttf
          weight: 700
